# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: demo

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo hello world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  my_first_job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Run a single-line script
        run: echo "hello world!"
  
  my_second_job:
    name: my second job
    runs-on: macos-latest

    steps:
      - name: Run a multi-line script
        env:
          MY_VAR: hello world!
          MY_NAME: YSP
        run:
          echo $MY_VAR
          echo my name is $MY_NAME



# name: Node.js CI
# on: push

# jobs:
#   my-job:
#     name: My job
#     runs-on: ubuntu-latest
#     steps:
#     - name: Print a greeting
#       env:
#         MY_VAR: Hi there! my name is 
#         FIRST_NAME: YSP
#         MIDDLE_NAME: the
#         LAST_NAME: Octocat
#     - run: |
#         echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME


# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # steps:
    # - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
